---
name: DiscordRelayPMMP
main: vortex/DiscordRelay/main
version: 1.0.10
api:
- 4.0.6
author: DaBoltGod
description: Send console to a discord server
website: https://github.com/daboltgod/discord-relay-pmmp
commands:
  drversion:
    description: Version command
    usage: /drversion
    permission: mcpediscordrelay.command.drversion
  drinfo:
    description: Information Command
    usage: /drinfo
    permission: mcpediscordrelay.command.drinfod
permissions:
  mcpediscordrelay.command.drversion:
    description: Shows the version info of the plugin
    default: true
  mcpediscordrelay.command.drinfo:
    description: Shows the basic info of the plugin
    default: true
...
